export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;
export const CLOUDINARY_URL = process.env.NEXT_PUBLIC_CLOUDINARY_URL;
export const CLOUDINARY_API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET;