export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;

// CLOUDINARY
export const CLOUDINARY_API_KEY = process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = process.env.NEXT_PUBLIC_CLOUDINARY_SECRET;

export const CLOUDINARY_URL = process.env.NEXT_PUBLIC_CLOUDINARY_URL;
export const CLOUDINARY_DESTROY_URL = process.env.NEXT_PUBLIC_CLOUDINARY_DESTROY;
export const CLOUDINARY_DEFAULT_IMAGE = process.env.NEXT_PUBLIC_CLOUDINARY_DEFAULT_IMG;